<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <!-- async/await -->
    <script>
        // resolve : 작업 성공 
        // reject : 작업 실패
    // function consolePrint() {
    //     return new Promise(function(resolve, reject) {
    //         setTimeout(function() {
    //             // const user = {name: '홍길동', age:19}
    //             resolve(user);
    //         }, 2000)
    //     })
    // }

    // consolePrint()
    //     .then(result => console.log(result)) // resolve일때
    //     .catch(error => console.log(error)); // reject일때

    // async function getPrint() {
    //     try {
    //         const result = await consolePrint();
    //         console.log("실행 완료 : " + result);
    //     }
    //     catch(error) {
    //         console.log("에러 발생 : " + error);
    //     }

    //     console.log("코드 실행");
    // }

    // getPrint();
    // console.log("함수 호출 완료");


    // 1) 콜백함수를 이용하여 1초뒤 사용자의 이름을 출력하는 코드
    getUserData(function(result) {
        console.log(result);
    })

    function getUserData(collback) {  
        setTimeout( () => {
            const userName = "홍길동";
            collback(userName); 
        }, 1000)
    }


    // 2) 프로미스를 이용하여 성공할 경우 data출력, 실패할 경우 "실패했습니다." 출력
    //    성공/실패의 여부는 successCheck 변수의 값에 따라 변경
    function fetchData(successCheck) {
        return new Promise((resolve, reject) => {
            const data = "이것은 데이터입니다.";

            if(successCheck) {
                resolve(data);
            }
            else {
                reject("실패했습니다.");
            }
        })
    }
    fetchData(false)
        // .then(function(result) {consloe.log(result)})  -> 아래코드와 같음
        .then(result => console.log(result))
        .catch(error => console.log(error));


    // 3) 홀수일 경우 then으로 받는 결과는 "홀수입니다" 출력
    //    짝수일 경우 catch로 받는 결과를 " 짝수입니다." 출력
    function checkOddEven(number) {
        return new Promise((resolve, reject) => {
            if(number % 2 === 1) {
                resolve("홀수입니다.")
            }
            else {
                reject("짝수입니다.")
            }
        })
    }

    checkOddEven(10)
        .then(function(result) {
            console.log(result)
        }) // 일반함수
        .catch(error => console.log(error)); // 화살표 함수 (=>를 function으로 )


    // 4)
    // 2초 뒤 이메일을 반환
    function getUserByEmail() {
        const email = "test@example.com";
        console.log("return 전");
        
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                console.log("setTimeOut 전");
                resolve(email);
                console.log("setTimeOut 후");
            }, 2000)
        })
    }
 
        

    async function emailPrint() {

        try {
            // async/await를 사용하여 getUserByEmail 함수 호출 후 이메일 출력
            console.log("await 실행 전");
            const result = await getUserByEmail();
            console.log("await 실행 후 : " + result);
        }
        catch {
            console.log("catch");

        }
    }
    
    console.log("------------------------------");
    console.log("함수 호출 전");
    emailPrint();
    console.log("함수 호출 후");

    </script>
</body>
</html>